# Server configuration
server:
  port: 8080
  contextPath: /sandbox

# See http://docs.spring.io/spring-boot/docs/1.2.1.RELEASE/reference/htmlsingle/#boot-features-custom-log-levels
logging:
  level:
    org.springframework.web=INFO
    bcp.spring=DEBUG
